Feat/patrik/polls
FHA-FB5/DC-Universe pull request #35
Opened 2020-10-20 22:15 UTC by Rec0gnice

2020-10-20 23:55 UTC, TitusKirch requested changes

2020-10-20 23:55 UTC, TitusKirch commented on extensions/polls.py
> +        if payload.emoji.name != '✅' and payload.emoji.name != '❌' and self.emojis.count(payload.emoji.name) == 0:
Why is that? Doesn't this now remove all reactions except the ones listed?

2020-10-21 06:09 UTC, Rec0gnice commented on extensions/polls.py
> +        if payload.emoji.name != '✅' and payload.emoji.name != '❌' and self.emojis.count(payload.emoji.name) == 0:
Yes, because like this you do not need a database connection

2020-10-21 11:25 UTC, TitusKirch commented on extensions/polls.py
> +        if payload.emoji.name != '✅' and payload.emoji.name != '❌' and self.emojis.count(payload.emoji.name) == 0:
But this removes the reactions from all messages, not only from the polls

2020-10-21 14:53 UTC, Rec0gnice commented on extensions/polls.py
> +        if payload.emoji.name != '✅' and payload.emoji.name != '❌' and self.emojis.count(payload.emoji.name) == 0:
Ah yes, I thought that I get it from the payload, but that can be anything :D but than I have to also store the message_ID with the state in the database. Like the problem solved in #39.

2020-10-21 15:30 UTC, TitusKirch commented on extensions/polls.py
> +        if payload.emoji.name != '✅' and payload.emoji.name != '❌' and self.emojis.count(payload.emoji.name) == 0:
No, even this does not help, since there can be several surveys at the same time. Just remove this feature (it doesn't have much added value)

2020-10-21 16:05 UTC, Rec0gnice commented on extensions/polls.py
> +        if payload.emoji.name != '✅' and payload.emoji.name != '❌' and self.emojis.count(payload.emoji.name) == 0:
So you want to allow people voting on controversial answers? I do not agree with that, because people when they have the chance to exploit those gaps to disturb others

2020-10-21 21:57 UTC, TitusKirch commented on extensions/polls.py
> +        if payload.emoji.name != '✅' and payload.emoji.name != '❌' and self.emojis.count(payload.emoji.name) == 0:
Yes, this was planned for the feature and works great on any large server. People who take advantage of this will simply be banned. You can also add a cooldown for the command.

2020-10-22 09:10 UTC, Rec0gnice commented on extensions/polls.py
> +        if payload.emoji.name != '✅' and payload.emoji.name != '❌' and self.emojis.count(payload.emoji.name) == 0:
I did delete the event then.

2020-10-22 09:33 UTC, TitusKirch approved these changes

2020-10-22 09:53 UTC, merged