Fix/patrik/refactor
FHA-FB5/DC-Universe pull request #96
Opened 2020-11-02 15:48 UTC by Rec0gnice

belongs to #95

2020-11-05 10:53 UTC, TitusKirch requested changes
I currently see no reason for a 'util.py' (at least not like you use it). So we would have an inconsistent behaviour/implementation of the same activities.

If I were to merge this into the main, it would only make more work for me if I were to rebuild the bot for after the initial time. So you would either replace all create embends or do without them here. But I can't tell you whether it will be removed completely later on.

2020-11-05 10:53 UTC, TitusKirch commented on extensions/error.py
> +            embed = await create_embed( 'Dieser Befehl kann nur von Admins ausgeführt werden!',
"Für diesen Befehl hast du nicht die benötigten Berechtigungen!"

2020-11-05 11:40 UTC, Rec0gnice commented
> I currently see no reason for a 'util.py' (at least not like you use it). So we would have an inconsistent behaviour/implementation of the same activities.
> 
> If I were to merge this into the main, it would only make more work for me if I were to rebuild the bot for after the initial time. So you would either replace all create embends or do without them here. But I can't tell you whether it will be removed completely later on.

The util function will be there no matter what, so I started laying down some basic functions. I don't mind if I personally have to change every embed creation later on

2020-11-07 15:23 UTC, TitusKirch approved these changes

2020-11-07 15:23 UTC, merged